spring:
  application:
    name: sb01-hrbank-team04
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성 (기존 테이블 유지)
    database: postgresql
  transaction:
    default-timeout: 30
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hrbank  # 새로운 DB 이름 적용
    username: hrbank_admin  # 새로운 사용자 적용
    password: "!hrbank_admin@04" # 새로운 비밀번호 적용

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# swagger
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true
